"""Synthetic row_batch generation for instant decode replay.

Replay re-streams an already-decoded, cached result as a paced sequence of
the same WS event types the real decode emits, without touching the audio
file. Row previews are generated by downsampling the *final* saved PNG
(already correctly oriented and contrast-stretched) rather than raw decode
order — this actually looks better than the original live-decode preview.
"""

from __future__ import annotations

import base64
from pathlib import Path

import numpy as np
from PIL import Image

PREVIEW_WIDTH = 825
ROWS_PER_BATCH_TARGET = 12


def build_row_batches(png_path: Path, global_index: int) -> list[dict]:
    img = Image.open(png_path).convert("L")
    w, h = img.size
    scale = PREVIEW_WIDTH / w
    preview_h = max(1, round(h * scale))
    img = img.resize((PREVIEW_WIDTH, preview_h))
    arr = np.array(img, dtype=np.uint8)

    batch_count = min(ROWS_PER_BATCH_TARGET, preview_h) or 1
    rows_per_batch = max(1, -(-preview_h // batch_count))  # ceil division

    batches: list[dict] = []
    row_start = 0
    for i in range(0, preview_h, rows_per_batch):
        chunk = arr[i: i + rows_per_batch]
        batches.append({
            "type": "row_batch",
            "global_index": global_index,
            "row_start": row_start,
            "row_count": chunk.shape[0],
            "width": PREVIEW_WIDTH,
            "pixels_b64": base64.b64encode(chunk.tobytes()).decode("ascii"),
            "provisional": True,
        })
        row_start += chunk.shape[0]
    return batches
